apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-httpd
  labels:
    app: httpd
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
        - name: httpd
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
