# parent-chart/values.yaml
nginx:
  enabled: true
  replicaCount: 2
  image:
    repository: nginx
    tag: "latest"

mongodb:
  enabled: false
  replicaCount: 3
  image:
    repository: bitnami/mongodb
    tag: "5.0"

elasticsearch:
  enabled: false
  replicaCount: 2
  image:
    repository: bitnami/elasticsearch
    tag: "7.10"

mysql:
  enabled: false
  replicaCount: 2
  image:
    repository: bitnami/mysql
    tag: "8.0"
httpd:
  enabled: false # Set to true to enable HTTPD
  replicaCount: 2 # Customize replica count for HTTPD
  image:
    tag: "latest" # Update HTTPD version if necessary
  service:
    port: 8080 # Customize the HTTPD service port
